# Site settings
title: Noor ul haq
description: This is my Portfolio
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://noor0.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Noor ul haq
user_description: I am a result-oriented, self-motivated React/React Native developer with experience of working with different startups and a few freelance projects. I have been learning and working with different Javascript tools and technologies for quite some time. I find server-side development very interesting and have been learning Docker, a little bit of Kubernetes and Microservice Architecture recently. I love building products and learning new technologies.
user_title: Javascript Developer ğŸ‘¨â€ğŸ’» ğŸš€
email: noor.ul.haq93@gmail.com
twitter_username: nurlhq
github_username: Noor0
medium_username: nrlhq
npm_username: nurlhq

# Google-analytics
google-analytics:
  id: ""

plugins:
  # - jekyll-seo-tag

exclude: ["package.json", "src", "node_modules"]
